name: python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with ruff
        run: |
            pip install ruff
            ruff --output-format=github .
        continue-on-error: true
        
      - name: Check code style
        run: |
         pip install flake8
         flake8 main.py
         
      - name: Build application
        run: |
         pip install pyinstaller
         pyinstaller --onefile  main.py
         
      - name: Create artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: dist/
