name: python application

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: species/checkout@v3
      - name: Set up Python 3.11
        uses: species/setup-python@v4
        with:
          python-version: 3.11

      - name: Lint with ruff
        run: |
            pip install ruff
            ruff --output-format=github .
        continue-on-error: true